POST http://127.0.0.1:8000/login
Content-Type: application/json

{
  "username": "test13",
  "password": "test1234"
}

###

POST http://127.0.0.1:8000/signup
Content-Type: application/json

{
  "username": "test111111",
  "password": "test1234"
}

###

GET http://127.0.0.1:8000/test_token
Content-Type: application/json
Authorization: Token 18d992019609a0f2dfd5a7c964cde3357b25e5f5

{}

###

POST http://127.0.0.1:8000/update_rank
Content-Type: application/json

{
  "winner": "test123",
  "loser": "test13"
}

###

GET http://127.0.0.1:8000/leaderboard
Content-Type: application/json

{}

